blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_TOOLCHAIN_FILE=/root/model_car/catkin_ws/src/Toolchain-arm-linux-gnueabihf.cmake
devel_layout: merged
devel_space: devel
extend_path: /opt/odroid-x2/sdk/opt/ros/indigo
install: true
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
